{
  "original_file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\emergency_eventbus_deduplication_recovered_2.py",
  "quarantine_timestamp": "2025-06-21T04:33:34.493683+00:00",
  "violations": [
    {
      "rule_type": "no_fallback_logic",
      "pattern": "try:",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\emergency_eventbus_deduplication_recovered_2.py",
      "line_numbers": [
        48,
        147
      ],
      "violation_count": 2
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "except Exception",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\emergency_eventbus_deduplication_recovered_2.py",
      "line_numbers": [
        82,
        151
      ],
      "violation_count": 2
    },
    {
      "rule_type": "no_fallback_logic",
      "pattern": "else:",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\emergency_eventbus_deduplication_recovered_2.py",
      "line_numbers": [
        98,
        172
      ],
      "violation_count": 2
    },
    {
      "rule_type": "eventbus_required",
      "pattern": "emit(",
      "file": "c:\\Users\\patra\\Genesis FINAL TRY\\modules\\unclassified\\emergency_eventbus_deduplication_recovered_2.py",
      "line_numbers": [
        38,
        157,
        160,
        189
      ],
      "violation_count": 4
    }
  ],
  "quarantine_reason": "ARCHITECT_MODE_VIOLATION"
}